name: Build and Commit Eleventy Site to Main

on:
  workflow_dispatch: # This makes the workflow manually triggerable

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    permissions:
      contents: write # Grant write permission to the GITHUB_TOKEN for committing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest' # Updated to use the latest Node.js version

      - name: Install npm dependencies
        run: npm install # Install all dependencies listed in package.json

      - name: Build Eleventy site
        run: npx @11ty/eleventy

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          timestamp=$(date -u)
          git commit -m "${timestamp}" || exit 0
          git pull --rebase
          git push
